### ISSUE TITLE
No module named 'pysnmp'

### ISSUE THREAD

**Issue by cbho** [turboc1208/printermonitor#2]
Using the latest version of your app on hass.io 0.86.4 running in a Docker container.
SNMP is available in Home Assistant - the "[Printer Uptime Sensor](https://www.home-assistant.io/components/sensor.snmp/#printer-uptime-minutes)" works fine - but get this error message in the App Daemon log:

```
2019-02-06 21:41:30.215284 INFO AppDaemon: Initializing app printermonitor using class printermonitor from module printermonitor
2019-02-06 21:41:30.217655 WARNING AppDaemon: ------------------------------------------------------------
2019-02-06 21:41:30.217943 WARNING AppDaemon: Unexpected error initializing app: printermonitor:
2019-02-06 21:41:30.218318 WARNING AppDaemon: ------------------------------------------------------------
2019-02-06 21:41:30.219444 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 2051, in check_app_updates
    self.init_object(app)
  File "/usr/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 1567, in init_object
    modname = __import__(app_args["module"])
  File "/config/appdaemon/apps/printermonitor/printermonitor.py", line 45, in <module>
    from pysnmp.hlapi import *
ModuleNotFoundError: No module named 'pysnmp'
2019-02-06 21:41:30.219766 WARNING AppDaemon: ------------------------------------------------------------
```

Suggestions?
Related to running in a Docker environment, perhaps?

**Comment by turboc1208** [comment]
Check your homeassistant/lib/python3.6/site_packages directory and see if you have pysnmp installed.  if not, try installing that.  It's hard to keep track of what I installed vs what other homeassistant things installed and I took advantage of.  This may be one of the later.

**Comment by turboc1208** [comment]
any luck

**Comment by cbho** [comment]
Sorry for the delay - work kept me busy...

Looking in the `hassio/homeassistant` directory, I don't find any directory named lib.
I can find `homeassistant/deps/lib/python3.6/site-packages` - which has subfolders `pyupdate` and `pyupdate-0.2.21.dist-info`
If that's the correct folder, then there's not any pysnmp in there...

The Printer Uptime Sensor mentioned above is working, though...

Opened at Terminal instance on the machine and did `pip install pysnmp` (in as su) and it says:
```
Requirement already satisfied: pycryptodomex in /usr/local/lib/python2.7/dist-packages (from pysnmp)
Requirement already satisfied: pysmi in /usr/local/lib/python2.7/dist-packages (from pysnmp)
Requirement already satisfied: pyasn1>=0.2.3 in /usr/local/lib/python2.7/dist-packages (from pysnmp)
Requirement already satisfied: ply in /usr/local/lib/python2.7/dist-packages (from pysmi->pysnmp)
```

Have restarted Home Assistant (and also rebooted the entire machine).
Still, I get the following errors in AppDaemon:

```
2019-02-11 21:37:37.376662 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/printermonitor/printermonitor.py
2019-02-11 21:37:37.378618 WARNING AppDaemon: ------------------------------------------------------------
2019-02-11 21:37:37.378889 WARNING AppDaemon: Unexpected error loading module: /config/appdaemon/apps/printermonitor/printermonitor.py:
2019-02-11 21:37:37.379036 WARNING AppDaemon: ------------------------------------------------------------
2019-02-11 21:37:37.381686 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 2026, in check_app_updates
    self.read_app(mod["name"], mod["reload"])
  File "/usr/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 1809, in read_app
    self.modules[module_name] = importlib.import_module(module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/appdaemon/apps/printermonitor/printermonitor.py", line 45, in <module>
    from pysnmp.hlapi import *
ModuleNotFoundError: No module named 'pysnmp'

2019-02-11 21:37:37.381955 WARNING AppDaemon: ------------------------------------------------------------
2019-02-11 21:37:37.382149 WARNING AppDaemon: Removing associated apps:
2019-02-11 21:37:37.383000 WARNING ------------------------------------------------------------
2019-02-11 21:37:37.383296 WARNING Unexpected error during run()
2019-02-11 21:37:37.383502 WARNING ------------------------------------------------------------
2019-02-11 21:37:37.386568 WARNING Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 2026, in check_app_updates
    self.read_app(mod["name"], mod["reload"])
  File "/usr/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 1809, in read_app
    self.modules[module_name] = importlib.import_module(module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/appdaemon/apps/printermonitor/printermonitor.py", line 45, in <module>
    from pysnmp.hlapi import *
ModuleNotFoundError: No module named 'pysnmp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/appdaemon/admain.py", line 105, in run
    loop.run_until_complete(asyncio.gather(*pending))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/usr/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 1402, in utility
    await utils.run_in_executor(self.loop, self.executor, self.check_app_updates)
  File "/usr/lib/python3.6/site-packages/appdaemon/utils.py", line 125, in run_in_executor
    response = list(completed)[0].result()
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 2038, in check_app_updates
    if self.app_config[app]["module"] == module:
TypeError: string indices must be integers

2019-02-11 21:37:37.386898 WARNING ------------------------------------------------------------
2019-02-11 21:37:37.387082 INFO AppDeamon Exited
```

If the above makes any sense to you and you have advice, then I'm all ears - but it is also absolutely ok, if not - still, would be nice if I could get it to work :-)
Thanks in advance,
Chr.

**Comment by turboc1208** [comment]
What type of environment are you running in?  Hassio, HA in a docker environment, HA in a virtual machine, etc?

**Comment by cbho** [comment]
Hass.io 0.86.1 running in a docker environment on Debian Stretch 9 on an Intel NUC

**Comment by turboc1208** [comment]
hass.io, there is the problem.  Because of the way hassio locks things down, you can't install pysnmp with it.  I have put in a PR to request that it be included with the next release of the appdaemon addon for hass.io.  Sorry

**Comment by cbho** [comment]
No worries - thanks for your effort - and the explanation - I'll just wait 'till then pysnmp is included in appdaemon :-)

**Comment by turboc1208** [comment]
It looks like there is something in the configuration section of addon-appdaemon3 that allows you to add it from there.
https://github.com/hassio-addons/addon-appdaemon3#configuration

**Comment by cbho** [comment]
Finally I got the time to look at this again...

These were the packages that were needed:
```
  "system_packages": [
    "gcc",
    "libc-dev"
  ],
  "python_packages": [
    "stdio-mgr",
    "pysnmp"
  ],
```
